---
- hosts: all
  become: true
  tasks:
    - name: Update the System Packages
      yum:
        upgrade: yes
        update_cache: yes

    - name: Install Java
      yum:
        name: default-jdk
        state: present

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: Tomcat download
      get url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.72/bin/apache-tomcat-9.0.72-fulldocs.tar.gz 
        dest: /opt/tomcat

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory
    
    - name: Copy Tomcat service from local to remote
      copy:
        src: /etc/tomcat.service
        dest: /etc/systemd/system/
         mode: 0755
    
    - name: start Tomcat
      service: name=tomcat state=started enabled=yes



